<?php
echo "# vim:ft=kitty\n";
echo "\n";
echo "## name: $theme_name Dark\n";
echo "## author: $theme_author (https://github.com/$theme_author_github_name)\n";
echo "## license: $theme_license\n";
echo "## upstream: $theme_upstream_url-dark.conf\n";
echo "## blurb: $theme_description\n";
echo "\n";
echo "\n";
echo "#: The basic colors\n";
echo "\n";
echo "foreground $B2T_A6\n";
echo "background $B2T_A0\n";
echo "selection_foreground $B2T_A6\n";
echo "selection_background $B2T_A1\n";
echo "\n";
echo "\n";
echo "#: Cursor colors\n";
echo "\n";
echo "cursor $B2T_D0\n";
echo "cursor_text_color $B2T_A0\n";
echo "\n";
echo "\n";
echo "#: URL underline color when hovering with mouse\n";
echo "\n";
echo "url_color $B2T_B6\n";
echo "\n";
echo "\n";
echo "#: kitty window border colors and terminal bell colors\n";
echo "\n";
echo "active_border_color $B2T_A2\n";
echo "inactive_border_color $B2T_A0\n";
echo "bell_border_color $B2T_B0\n";
echo "visual_bell_color none\n";
echo "\n";
echo "\n";
echo "#: OS Window titlebar colors\n";
echo "\n";
echo "wayland_titlebar_color $B2T_A1\n";
echo "macos_titlebar_color $B2T_A1\n";
echo "\n";
echo "\n";
echo "#: Tab bar colors\n";
echo "\n";
echo "active_tab_foreground $B2T_C7\n";
echo "active_tab_background $B2T_A0\n";
echo "inactive_tab_foreground $B2T_C3\n";
echo "inactive_tab_background $B2T_A1\n";
echo "tab_bar_background $B2T_A1\n";
echo "tab_bar_margin_color none\n";
echo "\n";
echo "\n";
echo "#: Colors for marks (marked text in the terminal)\n";
echo "\n";
echo "mark1_foreground $B2T_A0\n";
echo "mark1_background $B2T_B1\n";
echo "mark2_foreground $B2T_A0\n";
echo "mark2_background $B2T_C1\n";
echo "mark3_foreground $B2T_A0\n";
echo "mark3_background $B2T_D1\n";
echo "\n";
echo "\n";
echo "#: The basic 16 colors\n";
echo "\n";
echo "#: black\n";
echo "color0 $B2T_A0\n";
echo "color8 $B2T_A3\n";
echo "\n";
echo "#: red\n";
echo "color1 $B2T_B2\n";
echo "color9 $B2T_D5\n";
echo "\n";
echo "#: green\n";
echo "color2 $B2T_D4\n";
echo "color10 $B2T_A1\n";
echo "\n";
echo "#: yellow\n";
echo "color3 $B2T_D7\n";
echo "color11 $B2T_A2\n";
echo "\n";
echo "#: blue\n";
echo "color4 $B2T_B3\n";
echo "color12 $B2T_A4\n";
echo "\n";
echo "#: magenta\n";
echo "color5 $B2T_D4\n";
echo "color13 $B2T_B6\n";
echo "\n";
echo "#: cyan\n";
echo "color6 $B2T_B4\n";
echo "color14 $B2T_D3\n";
echo "\n";
echo "#: white\n";
echo "color7 $B2T_A6\n";
echo "color15 $B2T_B7\n";
